### PR TITLE
Fixed: code by adding css to ion-content to remove the overlapping of icon and text(#431)

### LINKED ISSUE #431: Icon overlaps text on 'Review Shipment' Page when scrolling to bottom of screen.
## Expected behavior
When scrolling down to the bottom of the 'Review Shipment' page, all elements, including icons and text, should remain properly spaced and displayed without overlapping. Users should be able to read the text without any visual obstruction caused by overlapping elements.

## Steps to reproduce the issue
Log in the App with valid credentials.
Go to Transfer Orders(TO) section and open any TO.
Manually enter the quantity for shipment for multiple products or simply scan the products and then update their quantity.
Navigate to the "Review Shipment" page.
Scroll down to the bottom of screen.
Observe the issue.

## Environment details
App version: TRANSFER-ORDER-UI-451FBD7
App Environment: UAT

## Additional information
Screenshot 2024-02-27 at 12 20 43 PM

### PR DESCRIPTION
**Pull request by Ritika-Patel08**
### Related Issues

Related issue  #431 

### Short Description and Why It's Useful

Added css to ion content to remove the overlapping of icon and text to have better user experience.

### Screenshots of Visual Changes before/after (If There Are Any)

Before:
image

After : 
image

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

### CODE REVIEW

File: src/views/TransferShipmentReview.vue [hunk 1]
```diff
@@ -328,10 +328,13 @@
   </script>
   
   <style scoped>
-  ion-content > main {
+  ion-content{
```
Comment (amansinghbais) [inline src/views/TransferShipmentReview.vue:331]: Simplify css and dont change existing css.

File: src/views/TransferShipmentReview.vue [hunk 2]
```diff
@@ -328,7 +328,10 @@
...
+    --padding-bottom: 80px;
+  } 
+    ion-content > main {
```
Comment (amansinghbais) [inline src/views/TransferShipmentReview.vue:334]: Improve indentation.

Comment (Ritika-Patel08) [reply src/views/TransferShipmentReview.vue]: done.

**Review by amansinghbais — APPROVED** [review]

**Review by ymaheshwari1 — APPROVED** [review]
