### PR TITLE
Fixed: issue of same package being added when clicking add box button multiple times(#198)

### LINKED ISSUE #198: Adding a box to an order item results in same-name boxes in the Orders card
## Current behavior
When adding a box to an order item, the system currently adds boxes with the same name as the existing box, resulting in a poor user experience. 

## Expected behavior
When adding a box to an order item, a new unique box should be created every time.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
Screenshot 2023-07-13 at 7 02 23 PM

### PR DESCRIPTION
**Pull request by ymaheshwari1**
### Related Issues

Closes #198 

### Short Description and Why It's Useful

In the current scenario, when a user clicks the add box button multiple times, multiple boxes gets added with the same package name, resulting in wrong user experience. So created a flag `isAddingBox` on order level to know whether the box adding is in-process or completed and not make furthur api calls for adding the box untill the previous call is not completed.

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/ionic-bopis#contribution-guideline)

### CODE REVIEW

File: src/views/InProgress.vue [hunk 1]
```diff
@@ -711,6 +711,13 @@ export default defineComponent({
       return defaultBoxType;
     },
     async addShipmentBox(order: any) {
+      if(order.isAddingBox) {
```
Comment (adityasharma7) [inline src/views/InProgress.vue:714]: We should add toast message that already an action is going on

Comment (ymaheshwari1) [reply src/views/InProgress.vue:714]: Discussed we will disable the button instead of adding a toast.

**Review by adityasharma7 — APPROVED** [review]
